import type { Exercise } from './types';

export const exercises: Exercise[] = [
  {
    id: 'neck-tilt',
    name: 'Neck Side Tilt',
    description: 'Gentle side-to-side tilts to release neck tension',
    duration: 30,
    category: 'neck',
    instructions: [
      'Sit up straight with shoulders relaxed',
      'Slowly tilt your head to the right, bringing ear toward shoulder',
      'Hold for 10-15 seconds',
      'Return to center and repeat on the left side',
    ],
  },
  {
    id: 'neck-rotation',
    name: 'Neck Rotation',
    description: 'Gentle rotation to improve neck mobility',
    duration: 20,
    category: 'neck',
    instructions: [
      'Sit up tall with shoulders down',
      'Slowly turn your head to look over your right shoulder',
      'Hold for 5-10 seconds',
      'Return to center and repeat on the left side',
    ],
  },
  {
    id: 'chin-tuck',
    name: 'Chin Tuck',
    description: 'Strengthen neck muscles and counter forward head posture',
    duration: 25,
    category: 'neck',
    instructions: [
      'Sit or stand with good posture',
      'Keep eyes looking forward',
      'Gently draw your chin back, creating a "double chin"',
      'Hold for 5 seconds, repeat 5 times',
    ],
  },
  {
    id: 'shoulder-rolls',
    name: 'Shoulder Rolls',
    description: 'Release shoulder tension from desk work',
    duration: 30,
    category: 'shoulders',
    instructions: [
      'Sit or stand with arms relaxed at your sides',
      'Roll your shoulders forward in a circular motion 10 times',
      'Then roll them backward 10 times',
      'Move slowly and with control',
    ],
  },
  {
    id: 'shoulder-shrugs',
    name: 'Shoulder Shrugs',
    description: 'Release upper trapezius tension',
    duration: 25,
    category: 'shoulders',
    instructions: [
      'Sit or stand with good posture',
      'Raise your shoulders up toward your ears',
      'Hold for 3 seconds',
      'Release and drop shoulders down',
      'Repeat 5-8 times',
    ],
  },
  {
    id: 'shoulder-squeeze',
    name: 'Shoulder Blade Squeeze',
    description: 'Counter rounded posture and strengthen upper back',
    duration: 25,
    category: 'shoulders',
    instructions: [
      'Sit up straight',
      'Squeeze your shoulder blades together',
      'Hold for 5 seconds',
      'Release and repeat 5 times',
    ],
  },
  {
    id: 'wrist-flexor',
    name: 'Wrist Flexor Stretch',
    description: 'Release typing strain on inner forearm',
    duration: 30,
    category: 'wrists',
    instructions: [
      'Extend your right arm forward, palm facing up',
      'Use your left hand to gently pull your fingers back',
      'Hold for 10-15 seconds',
      'Switch hands and repeat',
    ],
  },
  {
    id: 'wrist-extensor',
    name: 'Wrist Extensor Stretch',
    description: 'Release mouse and keyboard strain',
    duration: 30,
    category: 'wrists',
    instructions: [
      'Extend your right arm forward, palm facing down',
      'Use your left hand to gently press fingers down',
      'Hold for 10-15 seconds',
      'Switch hands and repeat',
    ],
  },
  {
    id: 'wrist-circles',
    name: 'Wrist Circles',
    description: 'Improve wrist mobility and reduce stiffness',
    duration: 30,
    category: 'wrists',
    instructions: [
      'Extend arms in front of you',
      'Make gentle circles with your wrists',
      '5-10 circles clockwise',
      '5-10 circles counterclockwise',
    ],
  },
  {
    id: 'spinal-twist',
    name: 'Seated Spinal Twist',
    description: 'Release upper back tension and improve spine mobility',
    duration: 30,
    category: 'back',
    instructions: [
      'Sit up straight in your chair',
      'Place your right hand on the back of the chair',
      'Gently twist to the right, looking over your shoulder',
      'Hold for 10-15 seconds, repeat on the left side',
    ],
  },
  {
    id: 'thoracic-extension',
    name: 'Thoracic Extension',
    description: 'Open chest and counter hunched posture',
    duration: 30,
    category: 'back',
    instructions: [
      'Sit at the edge of your chair',
      'Interlace fingers behind your head',
      'Gently arch backward, looking up',
      'Hold for 3-5 seconds, repeat 5-8 times',
    ],
  },
  {
    id: 'cat-cow',
    name: 'Seated Cat-Cow',
    description: 'Mobilize the spine and relieve back stiffness',
    duration: 40,
    category: 'back',
    instructions: [
      'Sit on the edge of your chair with feet flat',
      'Place hands on knees',
      'Inhale and arch your back (cow pose)',
      'Exhale and round your back (cat pose)',
      'Repeat slowly 6-10 times',
    ],
  },
  {
    id: 'pelvic-tilt',
    name: 'Seated Pelvic Tilt',
    description: 'Release lower back tension from prolonged sitting',
    duration: 30,
    category: 'back',
    instructions: [
      'Sit up straight with feet flat on the floor',
      'Tilt your pelvis forward, arching your lower back',
      'Then tilt backward, rounding your lower back',
      'Repeat 10 times slowly',
    ],
  },
  {
    id: 'knee-to-chest',
    name: 'Seated Knee-to-Chest',
    description: 'Stretch lower back and hips',
    duration: 40,
    category: 'hips',
    instructions: [
      'Sit at the edge of your chair',
      'Lift your right knee toward your chest',
      'Hold with both hands for 10 seconds',
      'Lower and repeat with the left leg',
    ],
  },
  {
    id: 'standing-back-extension',
    name: 'Standing Back Extension',
    description: 'Counter seated posture and relieve lower back',
    duration: 25,
    category: 'back',
    instructions: [
      'Stand with hands on your lower back',
      'Gently arch backward, looking up',
      'Hold for 3 seconds',
      'Return to neutral and repeat 5 times',
    ],
  },
  {
    id: 'eye-20-20-20',
    name: '20-20-20 Rule',
    description: 'Reduce eye strain from screens',
    duration: 20,
    category: 'eyes',
    instructions: [
      'Look away from your screen',
      'Focus on something 20 feet away',
      'Hold your gaze for 20 seconds',
      'Blink naturally',
    ],
  },
  {
    id: 'blink-reset',
    name: 'Blink Reset',
    description: 'Rehydrate eyes and reduce dryness',
    duration: 15,
    category: 'eyes',
    instructions: [
      'Close your eyes gently',
      'Perform 10-15 deliberate, slow blinks',
      'Keep your face relaxed',
      'Resume normal blinking',
    ],
  },
  {
    id: 'eye-rolls',
    name: 'Eye Rolls',
    description: 'Release eye muscle tension',
    duration: 20,
    category: 'eyes',
    instructions: [
      'Look up and slowly circle your eyes clockwise',
      'Complete 5 full circles',
      'Then circle counterclockwise 5 times',
      'Keep head still, move only your eyes',
    ],
  },
];

export const painRoutines: Record<string, string[]> = {
  neck: ['neck-tilt', 'neck-rotation', 'chin-tuck'],
  shoulders: ['shoulder-rolls', 'shoulder-shrugs', 'shoulder-squeeze'],
  wrists: ['wrist-flexor', 'wrist-extensor', 'wrist-circles'],
  upperBack: ['spinal-twist', 'thoracic-extension', 'shoulder-squeeze'],
  lowerBack: ['pelvic-tilt', 'cat-cow', 'standing-back-extension'],
  eyes: ['eye-20-20-20', 'blink-reset', 'eye-rolls'],
};

export const quickRoutines = {
  deskReset: {
    name: 'Desk Reset',
    duration: 90,
    exercises: ['neck-tilt', 'shoulder-rolls', 'wrist-circles'],
  },
  postureCorrect: {
    name: 'Posture Correct',
    duration: 95,
    exercises: ['chin-tuck', 'shoulder-squeeze', 'thoracic-extension', 'cat-cow'],
  },
  screenBreak: {
    name: 'Screen Break',
    duration: 80,
    exercises: ['eye-20-20-20', 'neck-rotation', 'shoulder-shrugs'],
  },
};
